// Ghana delivery locations
export const GHANA_LOCATIONS = {
  'Greater Accra': [
    'Greater Accra (All)',
    'Accra Central',
    'Osu',
    'Labone',
    'Cantonments',
    'Airport Residential',
    'East Legon',
    'Adabraka',
    'Asylum Down',
    'Ridge',
    'Roman Ridge',
    'Dzorwulu',
    'North Ridge',
    'Kokomlemle',
    'Abelemkpe',
    'North Labone',
    'Labadi',
    'Teshie',
    'Nungua',
    'Spintex',
    'Tema',
    'Community 1 - Tema',
    'Community 25 - Tema',
    'Ashaiman',
    'Madina',
    'Adenta',
    'Dome',
    'Achimota',
    'Lapaz',
    'Kaneshie',
    'Dansoman',
    'Mamprobi',
    'Korle Bu',
    'Circle (Nkrumah Circle)',
    'Kwame Nkrumah Circle',
    'Kasoa',
    'Weija',
    'Gbawe',
    'Mallam',
    'Santa Maria',
    'Anyaa',
    'Ofankor',
    'Pokuase',
    'Amasaman',
    'Ablekuma',
    'Odorkor',
    'Abeka',
    'Darkuman',
    'New Fadama',
    'Agbogbloshie',
    'Bubuashie',
    'Caprice',
    'Banana Inn',
    'Legon',
    'Haatso',
    'Atomic',
    'Kwabenya',
    'Ashongman',
    'Taifa',
    'Oyarifa',
    'Pantang',
  ],
  'Ashanti': [
    'Kumasi (All)',
    'Kumasi',
    'Adum',
    'Asafo',
    'Bantama',
    'Nhyiaeso',
    'Ahodwo',
    'North Suntreso',
    'South Suntreso',
    'Suame',
    'Maakro',
    'Ayigya',
    'KNUST Campus',
    'Kentinkrono',
    'Ayeduase',
    'Maxima',
    'Tech Junction',
    'Ahinsan',
    'Asokwa',
    'Kwadaso',
    'Oforikrom',
    'Ejisu',
    'Mampong',
    'Offinso',
    'Konongo',
    'Juaben',
    'Bekwai',
  ],
  'Western Region': ['Western Region'],
  'Central Region': ['Central Region'],
  'Eastern Region': ['Eastern Region'],
  'Volta Region': ['Volta Region'],
  'Northern Region': ['Northern Region'],
  'Upper East Region': ['Upper East Region'],
  'Upper West Region': ['Upper West Region'],
  'Bono Region': ['Bono Region'],
  'Bono East Region': ['Bono East Region'],
  'Ahafo Region': ['Ahafo Region'],
  'Savannah Region': ['Savannah Region'],
  'North East Region': ['North East Region'],
  'Oti Region': ['Oti Region'],
  'Western North Region': ['Western North Region'],
};

export const ALL_LOCATIONS = Object.entries(GHANA_LOCATIONS).flatMap(([region, locations]) =>
  locations.map(location => ({
    region,
    location,
    label: location === region ? location : `${location} (${region})`,
    value: `${region}:${location}`,
  }))
);

export type Location = {
  region: string;
  location: string;
  label: string;
  value: string;
};
